inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Lint/RescueException:
  Exclude:
    - 'lib/libhoney/transmission.rb'
    - 'lib/libhoney/experimental_transmission.rb'

Metrics/BlockLength:
  Max: 35

Metrics/ClassLength:
  Max: 300
  Exclude:
    - lib/libhoney/transmission.rb # Should this remain so large?
    - test/*

Metrics/MethodLength:
  Max: 45
  Exclude:
    - lib/libhoney/transmission.rb
    - test/*

Metrics/LineLength:
  Max: 115
  Exclude:
    - lib/libhoney/client.rb
    - lib/libhoney/builder.rb

Metrics/AbcSize:
  Exclude:
    - test/*
