version: 2.0

test_steps: &test_steps
  - checkout
  - run:
      name: Force Bundler Version
      command: |
        sudo gem update --system
        echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
        source $BASH_ENV
        gem install bundler
  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
  - run:
      name: install dependencies
      command: |
        bundle install --jobs=4 --retry=3 --path vendor/bundle
  - save_cache:
      paths:
        - ./vendor/bundle
      key: v1-dependencies-{{ checksum "Gemfile.lock" }}
  - run:
      name: run rubocop
      command: bundle exec rake rubocop
  - run:
      name: run tests
      command: bundle exec rake test

# required as all of the jobs need to have a tag filter for some reason
tag_filters: &tag_filters
  filters:
      tags:
        only: /.*/

jobs:
  ruby-2.3:
    docker:
      - image: circleci/ruby:2.3
    steps: *test_steps
  ruby-2.4:
    docker:
      - image: circleci/ruby:2.4
    steps: *test_steps
  ruby-2.5:
    docker:
      - image: circleci/ruby:2.5
    steps: *test_steps
  ruby-2.6:
    docker:
      - image: circleci/ruby:2.6
    steps: *test_steps
  ruby-2.7:
    docker:
      - image: circleci/ruby:2.7
    steps: *test_steps
  publish:
    docker:
      # Just randomly pick one recent ruby version
      - image: circleci/ruby:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup Rubygems
          command: bash .circleci/setup-rubygems.sh
      - run:
          name: Publish to Rubygems
          command: |
            gem build libhoney.gemspec
            gem push "libhoney-$(git describe --tags | cut -d "v" -f 2).gem"

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - ruby-2.3: *tag_filters
      - ruby-2.4: *tag_filters
      - ruby-2.5: *tag_filters
      - ruby-2.6: *tag_filters
      - ruby-2.7: *tag_filters
  build:
    jobs:
      - ruby-2.3: *tag_filters
      - ruby-2.4: *tag_filters
      - ruby-2.5: *tag_filters
      - ruby-2.6: *tag_filters
      - ruby-2.7: *tag_filters
      - publish:
          requires:
            - ruby-2.3
            - ruby-2.4
            - ruby-2.5
            - ruby-2.6
            - ruby-2.7
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
